easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Game
        - App\Entity\Socity
        - App\Entity\User
        - App\Entity\Product
        - App\Entity\BalanceSheet
